- name: blockingfile module playbook
  hosts: all
  become: true
  tasks:
    - blockinfile:
        path: /mnt/block.txt
        create: yes
        block: |
          hello girish bhau
#note:- content unser the block will copy in nodes.