- name: playbook-6
  hosts: all

  become: true
  tasks:

  - name: installing-nginx
    apt:
       name: nginx
       state: latest


#Note:-#become true is for installing nginx replace with sudo, it works as a sudo command.

#  get ssh of node-1 and check if NGINX is running or not "systemctl status nginx"
