- name: webserver-playbook
  hosts: all
  become: true
  tasks:

  - name: installing web-sever                    #installing web-sever
    yum:
     name: httpd
     state: latest

  - blockinfile:                                  #Adding content into html page
     path: /var/www/html/index.html
     create: yes
     block: |
      Hello Rupam, How are you brother

  - name: start_httpd                              #starting httpd service
    systemd:
     name: httpd
     state: started

  # - name: restart_httpd
  #   systemd:
  #    name: httpd
  #    state: restarted