- name: playbook-6
  hosts: all
  #become true is for installing nginx replace with sudo, it works as a sudo command.
  become: true
  tasks:

  - name: installing-nginx
    apt:
      name: nginx
      state: latest
