- name: webserver-playbook
  hosts: all
  become: true
  tasks:

  - name: installing web-sever                    #installing web-sever
    yum:
     name: httpd
     state: latest

  - blockinfile:                                  #Adding content into html page
     path: /var/www/html/index.html
     create: yes
     block: |
      <H1>
        Hello Rupam, How are you brother
      </H1>
      
  - name: start_httpd                              #starting httpd service
    systemd:
     name: httpd
     state: started


     #NOTE:- 

  # - name: restart_httpd
  #   systemd:
  #    name: httpd
  #    state: restarted