- name: loop through pkg instllation playbook
  hosts: all
  become: true
  tasks:
  apt:

    - name: package instllation via loop modules
      apt:
        name: "{{item}}"
        state: latest
      loop: 
        - httpd
        - nginx
            

