- name: loop through pkg instllation playbook
  hosts: all
  become: true
  tasks:


   - name: package instllation via loop modules
     apt:
       name: "{{item}}"
       state: latest
     loop: 
       - apache2
       - nginx


