- name: Java for tOmcat
  hosts: all
  become: true
  tasks: 
  - name: update all
    yum:
     name: "*"
     state: latest
  - name: install java
    yum:
     name: java
     state: latest 
  - name: downloading tomcat
    get_url:
      url: "https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.81/bin/apache-tomcat-8.5.81.tar.gz"
      dest: /usr/local
  - name: unzip tomcat
    unarchive:
      src: "/usr/local/apache-tomcat-8.5.81.tar.gz"
      dest: /usr/local
      remote_src: yes    
  - name: Run Tomcat
    shell: nohup /usr/local/apache-tomcat-8.5.81/bin/startup.sh &


#Note:- we have to manually add 8080 port in security groups
#Note:- In ansible.conf file we have to change "Remote_user_name= centos/ubuntu according to Nodes AMI image"