- name: playbook for copy data from ansible-server to nodes
  hosts: all
  become: true
  vars:
    hello avengers: "writeanythig" 
  tasks:

    - name: copy data from source to destinationn
      template: 
        src: pravin.yml
        dest: /mnt/somkuwar.txt