- name: playbook for copy data from ansible-server to nodes
  hosts: all
  become: true
  vars:
    Hellow Avengers: rupam hai kahi dhoop zindagi, har pal yaha ji bhar jiyo, jo hai sama kl ho na ho....  # mention in file by: {{}}
  tasks:

    - name: copy data from source to destinationn
      template: 
        src: pravin.yml
        dest: /mnt/somkuwar.txt