- name: playbook for copy data from ansible-server to nodes
  hosts: all
  become: true
  vars:
    hello: "writeanythig" 
  #note:- In pravin.yml file {{}} only one word will take 
  tasks:

    - name: copy data from source to destinationn
      template: 
        src: pravin.yml
        dest: /mnt/somkuwar.txt