- name: playbook for copy data from ansible-server to nodes
  hosts: all
  become: true
  vars:
    hellow Avengers: rupam hai kahi dhoop  # mention in file by: {{}}
  tasks:

    - name: copy data from source to destinationn
      template: 
        src: pravin.yml
        dest: /mnt/somkuwar.txt