

- name: simple condition
  hosts: all
  become: true
  tasks:
    - name: print the task
      debug:
       msg: "Distribution name of Linux: {{ansible_distribution}}"
     

    - name: print any messages_1
      debug:
       msg: "print any msg"
     