---
# tasks file for tomcat_server

- name: Installation of required packages
  apt:
  update_cache: true 
     name: "{{item}}" 
     state: present
   
   loop:
        - unzip
        - openjdk-8-jre-headless
        